// Generated by CoffeeScript 1.3.3
(function() {
  var Bradbury;

  Bradbury = Backbone.Router.extend({
    routes: {
      "documents/:name": "show",
      "documents/:name/editor": "edit"
    },
    initialize: function() {},
    show: function(name) {},
    edit: function(name) {},
    markdownToHTML: function(markdown) {
      var _ref;
      if ((_ref = this.converter) == null) {
        this.converter = new Markdown.Converter();
      }
      return this.converter.makeHtml(markdown);
    }
  });

  Bradbury.alert = function(style, message) {};

  Bradbury.nextTick = function(fn) {
    return setTimeout(fn, 0);
  };

  $(document).ready(function() {
    var editor;
    window.Bradbury = new Bradbury();
    Backbone.history.start();
    editor = $("form.editor");
    return $("a").click(function() {
      return editor.show();
    });
  });

}).call(this);
